import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import FacilitySection from "@/components/FacilitySection";
import ReduxProvider from "@/components/ReduxProvider";
import "leaflet/dist/leaflet.css";
import { Toaster } from "@/components/ui/toaster";

const satoshi = localFont({
  src: [
    {
      path: "./fonts/satoshi/Satoshi-Black.woff",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/satoshi/Satoshi-Bold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/satoshi/Satoshi-Medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/satoshi/Satoshi-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/satoshi/Satoshi-Variable.woff",
      weight: "100 900",
      style: "normal",
    },
  ],
  variable: "--font-satoshi",
});

const gothics = localFont({
  src: "./fonts/gothic.woff",
  weight: "900",
  variable: "--font-gothics",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${satoshi.variable} ${gothics.variable}`}>
        <ReduxProvider>
          <Navbar />
          {children}
          <FacilitySection />
          <Footer />
          <Toaster />
        </ReduxProvider>
      </body>
    </html>
  );
}
